"""empty message

Revision ID: b8dc0d0c5b5a
Revises: 0abc9cd2f927
Create Date: 2019-12-02 21:32:33.220531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8dc0d0c5b5a'
down_revision = '0abc9cd2f927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('Artist', 'city_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('Venue', 'city_id', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'city_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('Artist', 'city_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_table('Show')
    # ### end Alembic commands ###
